### ISSUE TITLE
can not build on windows

### ISSUE THREAD

**Issue by lainswork** [bazelbuild/reclient#41] opened 2024-03-29 09:34 UTC
when i build reclient

Bazel uses ml64 to compile S file, but in reality, I have specified the compiler as GCC
Ultimately, ml64 was unable to parse assembly files from the gcc specification

![image](https://github.com/bazelbuild/reclient/assets/46841563/6dc45f06-c509-46f3-8484-62275c7c7de0)

**Comment by daniel-sudz** [comment] 2024-06-01 00:54
@gkousik I am able to reproduce this issue. Would upstream accept a PR for a fix?

**Comment by bentekkie** [comment] 2024-06-06 19:44
We use the llvm clang-cl toolchain to compile on windows.

Could you try the build after following https://bazel.build/configure/windows#clang

**Comment by bentekkie** [comment] 2024-06-06 20:01
Actually I reproduced it locally, will work on a fix

**Comment by bentekkie** [comment] 2024-06-07 14:07
https://github.com/bazelbuild/reclient/commit/f7132baa0a0f4f748d58eeed720a8bc27c6e0d0e should fix this, can you confirm?

**Comment by daniel-sudz** [comment] 2024-06-07 17:21
> You will need the clang-cl toolchain installed on your machine

I'm currently having some trouble getting bazel to find my clang-cl but this is unrelated to reclient. I pulled llvm from `choco` under `C:\\Program Files\\LLVM\\bin` and put it on my `action-env` path but something still seems wrong. 

Anyways I will debug this for a big and let you know if I still need something. Thanks again for the help!
```bash
C:\src\reclient>bazelisk build  --action_env "C:\\tools\\msys64\\usr\\bin;C:\\tools\\msys64\\bin;C:\\Windows;C:\\Windows\\System32;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\tools\\msys64\\mingw64\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\LLVM\\bin" --verbose_failures  --features=fastbuild //cmd/scandeps:scandeps_server
INFO: Analyzed target //cmd/scandeps:scandeps_server (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/containeradministrator/_bazel_containeradministrator/sd2lufjt/external/com_github_gflags_gflags/BUILD:18:15: Compiling src/windows_port.cc failed: (Exit 1): clang_installation_error.bat failed: error executing command (from target @com_github_gflags_gflags//:gflags)
  cd /d C:/users/containeradministrator/_bazel_containeradministrator/sd2lufjt/execroot/re_client
  SET CGO_ENABLED=0
    SET INCLUDE=clang_cl_not_found
    SET MSYS=winsymlinks:nativestrict
    SET PATH=clang_cl_not_found
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=clang_cl_not_found
    SET TMP=clang_cl_not_found
  external\local_config_cc\clang_installation_error.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_github_gflags_gflags /Ibazel-out/x64_windows-opt-ST-414e7db50cb1/bin/external/com_github_gflags_gflags /Ibazel-out/x64_windows-opt-ST-414e7db50cb1/bin/external/com_github_gflags_gflags/_virtual_includes/gflags /DBAZEL_CURRENT_REPOSITORY="com_github_gflags_gflags" /showIncludes /MT /Od /Z7 /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -Wno-builtin-macro-redefined /Gy /Gw /std:c++17 /O2 /std:c++17 -DGFLAGS_BAZEL_BUILD -DGFLAGS_INTTYPES_FORMAT_C99 -DGFLAGS_IS_A_DLL=0 -DHAVE_STDINT_H -DHAVE_SYS_TYPES_H -DHAVE_INTTYPES_H -DHAVE_SYS_STAT_H -DHAVE_STRTOLL -DHAVE_STRTOQ -DHAVE_RWLOCK -DOS_WINDOWS /Fobazel-out/x64_windows-opt-ST-414e7db50cb1/bin/external/com_github_gflags_gflags/_objs/gflags/windows_port.obj /c external/com_github_gflags_gflags/src/windows_port.cc
# Configuration: 68895c8d221616b8423e48421122698b196bea506377d331421240150d093fdb
# Execution platform: //:x64_windows

The target you are compiling requires the Clang compiler.
Bazel couldn't find a valid Clang installation on your machine.
Please check your installation following https://bazel.build/docs/windows#using
```

**Comment by daniel-sudz** [comment] 2024-06-07 17:34
> [f7132ba](https://github.com/bazelbuild/reclient/commit/f7132baa0a0f4f748d58eeed720a8bc27c6e0d0e) should fix this, can you confirm?

I think I'm seeing an issue similar to https://github.com/bazelbuild/bazel/issues/17863 now. Looking into it. 

```
ERROR: C:/users/containeradministrator/_bazel_containeradministrator/sd2lufjt/external/com_github_gflags_gflags/BUILD:18:15: Compiling src/windows_port.cc failed: undeclared inclusion(s) in rule '@com_github_gflags_gflags//:gflags':
this rule is missing dependency declarations for the following files included by 'src/windows_port.cc':
  'C:/Program Files/LLVM/lib/clang/18/include/vadefs.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stdarg.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stdarg___gnuc_va_list.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stdarg_va_list.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stdarg_va_arg.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stdarg___va_copy.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stdarg_va_copy.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stdarg.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stdarg.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stddef.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_ptrdiff_t.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_size_t.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_wchar_t.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_null.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_nullptr_t.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_max_align_t.h'
  'C:/Program Files/LLVM/lib/clang/18/include/__stddef_offsetof.h'
  'C:/Program Files/LLVM/lib/clang/18/include/limits.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stdarg.h'
  'C:/Program Files/LLVM/lib/clang/18/include/inttypes.h'
  'C:/Program Files/LLVM/lib/clang/18/include/stdint.h'
Target //cmd/scandeps:scandeps_server failed to build
INFO: Elapsed time: 11.929s, Critical Path: 1.53s
INFO: 8 processes: 8 internal.
FAILED: Build did NOT complete successfully
```

**Comment by daniel-sudz** [comment] 2024-06-07 17:42
@bentekkie created new issue in https://issues.chromium.org/issues/345627618 to bump bazel version.

**Comment by bentekkie** [comment] 2024-06-27 01:01
Closing this as we have a working GitHub actions build now

**Closed by bentekkie** 2024-06-27 01:01 UTC

**Comment by nishaanth-ms-21155** [comment] 2025-05-14 12:33
I have the same issue with MacOS on linux workers.

Is downloading linux toolchain sufficient. This is the output of reproxy.WARNING but Idk if its the reason for a lot of local fallbacks (99% local fallbacks)

```
W0514 17:57:11.841275   34547 server.go:722] 1013b7a6-6536-48b0-b549-ba9a7aa8f11c: Remote execution failed with &{ExitCode:1 Status:NonZeroExitResultStatus Err:<nil>}, falling back to local.
 stdout: 
 stderr: In file included from ../../third_party/libyuv/source/scale_any.cc:11:
In file included from ../../third_party/libc++/src/include/string.h:64:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/string.h:58:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/_string.h:61:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/_types.h:27:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/sys/_types.h:33:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/machine/_types.h:34:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/arm/_types.h:16:
In file included from sdk/xcode_links/MacOSX15.2.sdk/usr/include/sys/_types/_ptrdiff_t.h:41:
In file included from ../../third_party/libc++/src/include/stddef.h:38:
sdk/xcode_links/MacOSX15.2.sdk/usr/include/stddef.h:68:10: fatal error: 'sys/_types/_offsetof.h' file not found
   68 | #include <sys/_types/_offsetof.h>
```
